import DataLineffffbbbvvvcardinality_typeEController from '../data-line-ffffbbbvvv-cardinality-type-e';

var DataLineffffbbbvvvcardinality_typeENewController = DataLineffffbbbvvvcardinality_typeEController;
export default DataLineffffbbbvvvcardinality_typeENewController;
