import DataLineffffbbbvvvproduct_catalogEController from '../data-line-ffffbbbvvv-product-catalog-e';

var DataLineffffbbbvvvproduct_catalogENewController = DataLineffffbbbvvvproduct_catalogEController;
export default DataLineffffbbbvvvproduct_catalogENewController;
